apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-for-web-apps
  region: eu-west-3

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 40
    ssh:
      publicKeyPath: ~/.ssh/eks_nodes.pub
